# Add ESXi Hosts that you want to modify with the same information
esxi_info:
  - { name: '10.11.16.180', vmo: "10.11.17.180",  nfs_ip: "10.11.14.180", netmask: "255.255.255.0" }
 # - { name: '10.10.20.221', vmo: "10.10.40.221",  nfs_ip: "10.10.100.221", netmask: "255.255.255.0" }
 # - { name: '10.10.20.222', vmo: "10.10.40.222",  nfs_ip: "10.10.100.222", netmask: "255.255.255.0" }
 # - { name: 'iNUC04', vmo: "10.224.4.234",  nfs_ip: "10.224.5.234", netmask: "255.255.255.0" }
 # - { name: 'iNUC05', vmo: "10.224.4.235",  nfs_ip: "10.224.5.235", netmask: "255.255.255.0" }

#DNS and NTP
upstream_dns1: "10.11.20.11"
upstream_dns2: "10.11.20.12"
upstream_ntp1: "0.pool.ntp.org"
upstream_ntp2: "1.pool.ntp.org"

#Windows Server and Domain Controller Information
dc_hostname: DC1-SRV-CORE1
dc_address: "10.11.20.11"
domain_name: "e360demo.com"
ad_user: "admin.allen"
ad_password: "HDCadm1n^^"
esx_admins_group: "ESXi_Admins"

#VMware Infrastructure
#ESXi Host
esxi_address: "10.11.16.180"
esxi_password: "HDCadm1n^^"
esxi_netmask: "255.255.255.0"
esxi_netmask_cidr: "24"
esxi_gateway: "10.11.16.1"
esxi_hostname: "wcv-hst-esxi01"
esxi_username: "root"
esxi_local_datastore: "NFS_DS01"
ext_storage_ds_name: 'NFS_DS01'
ext_storage_ds_type: 'nfs'
ext_storage_nfs_server: '10.10.100.100'
ext_storage_nfs_path: 'NFS_DS01'
validate_certs: "no"
service_policy: 'pressent'
tsm_policy: 'on'
tsm_state: 'present'

# vCenter Info
vcenter_address: "10.10.50.240"
vcenter_gateway: "10.10.50.1"
vcenter_hostname: "IRV-VC02" #Name of VCSA Appliance
vcsa_size: "tiny"
shared_datastore: "NFS_DS01"
searchpath: "e360demo.com"
vcenter_username: "administrator@vsphere.local"
vcenter_password: 'ENT360adm1n^^'
vcenter_datacenter: "Datacenter"
vcenter_cluster: "E360Lab-A"
vCenter_License: M1621-49L00-08VGA-08AU0-0XLHN
vSphere_License: QH62N-NT19K-M8RG9-0H2UH-1D2M5

# Networking

#vSwitches for ESXi Hosts and vCenter Deployment without VDS
vSwitch0: "vSwitch0"
vSwitch1: "vSwitch1"
vSwitch2: "vSwitch2"

#VDS Network after vCenter is Deployed and Hosts are Added
vdswitchname: vDS01

#Management
mgmt_esx_pg: "Management Network"

#vMotion
vMotionPortGroup: "vMotionPortGroup"

#Storage Port Groups
#NFS
NFSPortGroup: "NFSPortGroup"
#iSCSI Network
iscsia_esx_vswitch: "iSCSIA_esx_switch"
iscsib_esx_vswitch: "iSCSIB_esx_switch"





# Networking VLAN ID


nfs_vlan: '100'
iscsi_vlana: '100'
iscsi_vlanb: '101'
vmotion_vlan: '40'
vdata_vlan: '50'



#Lab Nested Information
lab_domain: "mylab.tld"
lab_password: "HDCadm1n^^"
lab_netmask: "255.255.255.0"
lab_netmask_cidr: "24"
lab_gateway: "10.224.0.1"
lab_upstream_dns: "10.224.0.1"
temporary_password: "Changeme!"



#NetApp ONTAP Select Information
ontap_address: "10.224.0.30"
ontap_node_address: "10.224.0.31"
ontap_svm_address: "10.224.0.32"
ontap_hostname: "ontap"
ontap_memory_mb: 16348 # Minimum supported is 16gb, minimum working is 6gb.  8gb is suggested due to resource constraints on a NUC
ontap_num_vcpus: 4 # Minimum supported is 4.  Minimum working is 2.  4 may require more ram (>8gb) or a bootarg to set vnvram to 512.
ontap_data_disk_gb: "1000" #minimum usable is about 100gb, minimum supported is 1tb
ontap_svm_name: "svm1"
ontap_svm_lif: "svm1_lif1"
ontap_vol_labs: "labs"
ontap_vol_install: "install"
portal_home_dir: 'C:\vlab'
portal_sitename: 'Lab Portal'
portal_rdpdomain: 'LAB'
portal_rdpuser: 'administrator'

# FILES

files_path: "/Users/ajohnson/Ansible/NUCLab"
vaai_plugin: NetAppNasPlugin.v23.vib
#vcenter_ova: "VMware-vCenter-Server-Appliance-7.0.2.00200.ova"
vcenter_ova: "vcsa7.ova"
ontap_select_ova: "9.8_DataONTAPv-esx-standalone-eval-nodar.ova"
portal_ntap_pstk_msi: "NetApp_PowerShell_Toolkit_9.8.0.msi"
windows_iso: "17763.737.190906-2324.rs5_release_svc_refresh_SERVER_EVAL_x64FRE_en-us_1.iso"
#windows_iso_url: "http://software-download.microsoft.com/download/pr/Windows_Server_2016_Datacenter_EVAL_en-us_14393_refresh.ISO"
windows_iso_url: "https://software-download.microsoft.com/download/pr/17763.737.190906-2324.rs5_release_svc_refresh_SERVER_EVAL_x64FRE_en-us_1.iso"
windows_flp: server2019eval.flp
windows_flp_url: "http://github.madlabber.com/server2019eval.flp"