lab_domain: "mylab.tld"
lab_password: "HDCadm1n^^"
lab_netmask: "255.255.255.0"
lab_netmask_cidr: "24"
lab_gateway: "10.224.0.252"
lab_upstream_dns: "10.224.0.252"
temporary_password: "Changeme!"
esxi_address: "10.224.0.231"
esxi_password: "HDCadm1n^^"
dc_address: "10.224.0.10"
vcenter_address: "10.224.0.20"
ontap_address: "10.224.0.30"
ontap_node_address: "10.224.0.31"
ontap_svm_address: "10.224.0.32"
esxi_hostname: "iNUC01"
esxi_username: "root"
esxi_local_datastore: "iNUC01_NVME"
dc_hostname: dc01
vcenter_hostname: "vc01"
vcenter_username: "administrator@vsphere.local"
vcenter_datacenter: "Datacenter"
vcenter_cluster: "Cluster"
ontap_hostname: "OTS10"
ontap_memory_mb: 16348 # Minimum supported is 16gb, minimum working is 6gb.  8gb is suggested due to resource constraints on a NUC
ontap_num_vcpus: 4 # Minimum supported is 4.  Minimum working is 2.  4 may require more ram (>8gb) or a bootarg to set vnvram to 512.
ontap_data_disk_gb: "1000" #minimum usable is about 100gb, minimum supported is 1tb
ontap_svm_name: "svm1"
ontap_svm_lif: "svm1_lif1"
ontap_vol_labs: "LAB_DS01"
ontap_vol_install: "Install"
portal_home_dir: 'C:\vlab'
portal_sitename: 'Lab Portal'
portal_rdpdomain: 'LAB'
portal_rdpuser: 'administrator'
files_path: "/Users/ajohnson/Ansible/NUCLab"
vaai_plugin: NetAppNasPlugin.v23.vib
vcenter_ova: "vcsa7U2.ova"
ontap_select_ova: "9.9.1_DataONTAPv-esx-standalone-eval-nodar.ova"
portal_ntap_pstk_msi: "NetApp_PowerShell_Toolkit_9.8.0.msi"
windows_iso: "17763.737.190906-2324.rs5_release_svc_refresh_SERVER_EVAL_x64FRE_en-us_1.iso"
#windows_iso_url: "http://software-download.microsoft.com/download/pr/Windows_Server_2016_Datacenter_EVAL_en-us_14393_refresh.ISO"
windows_iso_url: "https://software-download.microsoft.com/download/pr/17763.737.190906-2324.rs5_release_svc_refresh_SERVER_EVAL_x64FRE_en-us_1.iso"
windows_flp: server2019eval.flp
windows_flp_url: "http://github.madlabber.com/server2019eval.flp"