esxi_info:
  - { name: '10.224.0.231' }
 # - { name: '10.224.0.232' }
 # - { name: '10.224.0.233' }
 # - { name: '10.224.0.234' }
 # - { name: 'iNUC05', vmo: "10.224.4.235",  nfs_ip: "10.224.5.235", netmask: "255.255.255.0" }

#VMware ESXI Host Information

esxi_hostname: "iNUC01" #If HostName is on DNS else use IP Address
esxi_username: "root"
esxi_address: "10.224.0.231"
esxi_password: "HDCadm1n^^" # Password
esxi_netmask: "255.255.255.0"
esxi_netmask_cidr: "24"
esxi_gateway: "10.224.0.252"
esxi_local_datastore: "iNUC04_DS01"
ext_storage_ds_name: 'OTS100_DS01'
ext_storage_ds_type: 'nfs'
ext_storage_nfs_server: '10.224.0.20'
ext_storage_nfs_path: 'OTS100_DS01'
validate_certs: "no"

#Active Directory Information
dc_address: "10.224.0.10"
dc_hostname: dc01
domain_name: "lab.local"
lab_domain: "mylab.tld"
ad_user: "Administrator"
ad_password: "P@ssw0rd"
lab_password: "P@ssw0rd"
lab_netmask: "255.255.255.0"
lab_netmask_cidr: "24"
lab_gateway: "10.224.0.252"
lab_upstream_dns: "10.224.0.252"
temporary_password: "Changeme!"
portal_home_dir: 'C:\vlab'
portal_sitename: 'Lab Portal'
portal_rdpdomain: 'LAB'
portal_rdpuser: 'administrator'

# VMware vCenter Info
vcenter_address: "10.224.3.20"
vcenter_gateway: "10.224.3.1"
vcenter_hostname: "vcsa-v7-A" #Name of VCSA Appliance
vcsa_size: "tiny"
shared_datastore: "iNUC04_DS01"
searchpath: "labb.local"
vcenter_username: "administrator@vsphere.local"
vcenter_password: 'P@ssw0rd'
vcenter_datacenter: "Datacenter"
vcenter_cluster: "HomeLab-A"
vCenter_License: M1621-49L00-08VGA-08AU0-0XLHN
vSphere_License: QH62N-NT19K-M8RG9-0H2UH-1D2M5

#NetApp ONTAP Information
ontap_address: "10.224.0.30"
ontap_node_address: "10.224.0.31"
ontap_svm_address: "10.224.0.32"
ontap_hostname: "OTS10"
ontap_memory_mb: 16348 # Minimum supported is 16gb, minimum working is 6gb.  8gb is suggested due to resource constraints on a NUC
ontap_num_vcpus: 4 # Minimum supported is 4.  Minimum working is 2.  4 may require more ram (>8gb) or a bootarg to set vnvram to 512.
ontap_data_disk_gb: "1000" #minimum usable is about 100gb, minimum supported is 1tb
ontap_svm_name: "svm1"
ontap_svm_lif: "svm1_lif1"
ontap_vol_labs: "LAB_DS01"
ontap_vol_install: "Install"

#DNS and NTP
upstream_dns1: "8.8.8.8"
upstream_dns2: "9.9.9.9"
upstream_ntp1: "0.pool.ntp.org"
upstream_ntp2: "1.pool.ntp.org"
service_policy: 'pressent'



# Networking 

vdswitchname: vDS01
vmdataPortGroup: "vmdata-103"
vMotionPortGroup: "vMotionPortGroup"
NFSPortGroup: "NFSPortGroup"
default_esx_pg: "Management Network"
default_esx_vswitch: "vSwitch0"
nfs_vlan: '105'
vmo_vlan: '104'
vdata_vlan: '103'
vmo_address: '10.224.4.31'
vmo_netmask: '255.255.255.0'

#Files 

files_path: "/Users/ajohnson/Ansible/NUCLab"
vaai_plugin: "NetAppNasPlugin.v23.vib"
#vcenter_ova: "VMware-vCenter-Server-Appliance-7.0.1.00200-17327517_OVF10.ova"
vcenter_ova: "vcsa7.ova"
ontap_select_ova: "9.9.1_DataONTAPv-esx-standalone-eval-nodar.ova"
portal_ntap_pstk_msi: "NetApp_PowerShell_Toolkit_9.8.0.msi"
windows_iso: "17763.737.190906-2324.rs5_release_svc_refresh_SERVER_EVAL_x64FRE_en-us_1.iso"
#windows_iso_url: "http://software-download.microsoft.com/download/pr/Windows_Server_2016_Datacenter_EVAL_en-us_14393_refresh.ISO"
windows_iso_url: "https://software-download.microsoft.com/download/pr/17763.737.190906-2324.rs5_release_svc_refresh_SERVER_EVAL_x64FRE_en-us_1.iso"
windows_flp: server2019eval.flp